name: coverage

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  codecov:
    runs-on: ubuntu-latest
    steps:
      - uses: snok/.github/workflows/codecov@main
        with:
          source-dir: flake8_type_checking
          pip-cache-key: pip-1
          poetry-cache-key: poetry-1
