name: coverage

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  codecov:
    runs-on: ubuntu-latest
    steps:
      - uses: snok/.github/workflows/codecov@sondrelg/codecov
        with:
          source-dir: flake8_type_checking
